package com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7 Mon Jun 24 13:02:28 CST 2013 Generated source version: 2.2.7
 */

@WebService(targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv", name = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv {

	@WebResult(name = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrvResponse", targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv", partName = "payload")
	@WebMethod(action = "process")
	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvResponse process(
			@WebParam(partName = "payload", name = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrvRequest", targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv") ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvRequest payload);
}
