/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.unicom.ucloud.UcloudRunner;
import com.unicom.ucloud.service.changnotice.ESBSFTNMSSFTNMSImportResChangeNoticeInfoSrvBusiness;

/**
 * This class was generated by Apache CXF 2.2.7 Mon Jun 24 13:02:28 CST 2013 Generated source version: 2.2.7
 */

@javax.jws.WebService(serviceName = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv", portName = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrvPort", targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv",
// wsdlLocation =
// "file:/G:/code/workSpaceEclipse/workSpaceEclipse/nbi_1_ucloub/Web/WEB-INF/META-INF/esb_sfwnos_sfwnos_00005/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv.WSDL",
endpointInterface = "com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv.ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv")
public class ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvImpl implements ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv {

	private static final Logger LOG = LoggerFactory.getLogger(UcloudRunner.class);

	/*
	 */
	public com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv.ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvResponse process(
			ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvRequest request) {
		ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvResponse response = null;
		LOG.info("Executing operation process");
		try {
			ESBSFTNMSSFTNMSImportResChangeNoticeInfoSrvBusiness business = new ESBSFTNMSSFTNMSImportResChangeNoticeInfoSrvBusiness();
			response = business.process(request);

		} catch (Exception ex) {
			String message = "ESB_SFWNOS_SFWNOS_00005: 导入资源变更通知信息服务(ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv)调用失败";
			if (response != null)
				response.setSERVICEMESSAGE(message);

			LOG.error(message);
		}
		return response;

	}

}
