package com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv;

import javax.xml.ws.Endpoint;

import com.unicom.ucloud.service.ServiceMgr;

/**
 * This class was generated by Apache CXF 2.2.7 Mon Jun 24 13:02:28 CST 2013 Generated source version: 2.2.7
 */

public class ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort_Server {

	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort_Server() throws Exception {

		System.out.println("Starting Server");
		Object implementor = new ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvImpl();
		ServiceMgr smgr = ServiceMgr.getInstance();
		String addressTmp = smgr.getWebserviceUrl("ESB_SFWNOS_SFWNOS_00005");

		String address = new String(addressTmp);
		address = address.replace("?wsdl", "").replace("?WSDL", "");

		// String address =
		// "http://localhost:8000/nbi/services/ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvImpl";
		Endpoint.publish(address, implementor);

	}

	public static void main(String args[]) throws Exception {
		new ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort_Server();
		System.out.println("Server ready...");

		Thread.sleep(5 * 60 * 1000);
		System.out.println("Server exiting");
		System.exit(0);
	}
}
