package com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.namespace.QName;

import com.unicom.ucloud.util.CalendarConverUtil;

/**
 * This class was generated by Apache CXF 2.2.7 Mon Jun 24 13:02:28 CST 2013 Generated source version: 2.2.7
 */

public final class ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort_Client {

	private static final QName SERVICE_NAME = new QName("http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv",
			"ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv");

	private ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort_Client() {
	}

	public static void main(String args[]) throws Exception {
		URL wsdlURL = ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service.WSDL_LOCATION;
		if (args.length > 0) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service ss = new ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service(wsdlURL, SERVICE_NAME);
		ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv port = ss.getESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort();

		{
			System.out.println("Invoking process...");
			ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvRequest request = new ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvRequest();
			MsgHeader header = new MsgHeader();
			header = null;
			/*
			 * header.setCURRENTPAGE(new BigDecimal(111)); header.setPAGESIZE(new BigDecimal(1)); header.setSOURCEAPPID("10");
			 * header.setSOURCEAPPNAME("11"); header.setSOURCEMODID("12"); header.setSOURCEMODNAME("13");
			 * header.setTARGETMODID("ESB_SFWNOS_SFWNOS_00005"); header.setTARGETMODNAME("ESB_SFWNOS_SFWNOS_00005"); header.setTOKEN("16");
			 * header.setUSERID(new BigDecimal(1)); header.setUSERNAME("18"); header.setSUBMITDATE(DateTest.convertToXMLGregorianCalendar(new
			 * Date())); header.setPAGESIZE(new BigDecimal(1)); header.setCURRENTPAGE(new BigDecimal(1)); header.setTOTALRECORD(new BigDecimal(107));
			 * header.setPROVINCECODE("19"); header.setENVIRONMENTNAME("SFWNOS_RM_NOTICE");
			 */

			request.setMsgHeader(header);
			ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputCollection value = new ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputCollection();

			List<ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputItem> esb = new ArrayList<ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputItem>();

			ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputItem item = new ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputItem();

			item.prikey = "1";
			item.noticetype = "6";
			item.noticexml = "<NOTICE_XML>		<WORK_ORDER_NO>1</WORK_ORDER_NO>		<OPER_TYPE>1</OPER_TYPE>		<PLAN_START_TIME>2013-03-03 00:00:00</PLAN_START_TIME>		<PLAN_END_TIME>2013-03-03 00:00:00</PLAN_END_TIME>		<ONLINEOPER_SCHEME>1</ONLINEOPER_SCHEME>		<AFFECT_NMS>1</AFFECT_NMS>		<AFFECT_SERVICE>1</AFFECT_SERVICE>		<AFFECT_SYSTEM>1</AFFECT_SYSTEM>		<AFFECT_RESOURCE>1</AFFECT_RESOURCE>		<RES_ID_LIST>				<RES_ID_ITEM>						<RES_ID>1</RES_ID>						<RES_CLASS_ID>1</RES_CLASS_ID>						<NMS_ID>1</NMS_ID>						<FLAG>2</FLAG>				</RES_ID_ITEM>				<RES_ID_ITEM>						<RES_ID>2</RES_ID>						<RES_CLASS_ID>2</RES_CLASS_ID>						<NMS_ID>2</NMS_ID>						<FLAG>2</FLAG>				</RES_ID_ITEM>				<!--RES_ID_ITEM的值，可为0~n个-->				<RES_ID_ITEM>						<RES_ID>3</RES_ID>						<RES_CLASS_ID>3</RES_CLASS_ID>						<NMS_ID>3</NMS_ID>						<FLAG>3</FLAG>				</RES_ID_ITEM>		</RES_ID_LIST></NOTICE_XML>";
			item.reserved1 = "1";
			item.reserved2 = "1";
			item.reserved3 = "1";
			item.reserved4 = "1";
			item.reserved5 = "1";
			item.reserved6 = "1";
			item.reserved7 = "1";
			item.reserved8 = "1";
			item.reserved9 = "1";
			item.reserved10 = "1";

			esb.add(item);

			value.getESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputItem().addAll(esb);

			request.setESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvInputCollection(value);

			ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvResponse _process__return = port.process(request);
			System.out.println("process.result=" + _process__return.getSERVICEFLAG());

		}

	}

}
