/*
 * 
 */

package com.unicom.ucloud.esb_sfwnos_sfwnos_importreschangenoticeinfosrv;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.unicom.ucloud.service.ServiceMgr;

/**
 * This class was generated by Apache CXF 2.2.7 Mon Jun 24 13:02:28 CST 2013 Generated source version: 2.2.7
 */

@WebServiceClient(name = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv",
// wsdlLocation =
// "file:/G:/code/workSpaceEclipse/workSpaceEclipse/nbi_1_ucloub/Web/WEB-INF/META-INF/esb_sfwnos_sfwnos_00005/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv.WSDL",
targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv")
public class ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv",
			"ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv");

	public final static QName ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort = new QName(
			"http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv", "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrvPort");
	static {

		URL url = null;
		try {
			// url = new
			// URL("http://localhost:8000/nbi/services/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv?wsdl");

			ServiceMgr smgr = ServiceMgr.getInstance();
			String address = smgr.getWebserviceUrl("ESB_SFWNOS_SFWNOS_00005");

			url = new URL(address);
		} catch (MalformedURLException e) {
			System.err.println("Can not initialize the default wsdl from file: ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv.WSDL");
			// e.printStackTrace();
		} catch (Exception e) {
			System.err.println("need to config wsdl    ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv.WSDL");
		}
		WSDL_LOCATION = url;
	}

	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * @return returns ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv
	 */
	@WebEndpoint(name = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrvPort")
	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv getESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort() {
		return super.getPort(ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort, ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv.class);
	}

	/**
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code>
	 *            parameter will have their default values.
	 * @return returns ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv
	 */
	@WebEndpoint(name = "ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrvPort")
	public ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv getESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort(WebServiceFeature... features) {
		return super.getPort(ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrvPort, ESBSFWNOSSFWNOSImportResChangeNoticeInfoSrv.class, features);
	}

}
