package com.unicom.ucloud.service.dao;

import java.text.SimpleDateFormat;

public class ESB_SFWNOS_SFWNOS_00001_DAO extends ESB_SFWNOS_SFWNOS_90001_DAO {

	private String sql = " select t.ne_sys_id PHYSICAL_DEVICE_ID , GONG_ANT TKSYS_NETWORK_BELONG_ENUM_ID ,t.ANT_PITCHANGLE ANTENNA_PITCHING_ANGLE, t.NE_SYS_ID  UPLINK_DEVICE_ID  , t.ANT_HIGH ANTENNA_HEIGHT , t.CELL_STATE MAINTENANCE_STATUS_ENUM_ID , t.ANT_AZIMUTH POSITION_ANGLE , t.ANT_PLUS ANTENNA_GAIN , ant.ANT_VENDOR ANTENNA_MANUFACTURER_ID  "
			+ ",null ELECTRIC_REGULATING_FLAG , null FEEDER_MANUFACTURER_ID ,null REGULATING_RCU_POSITION ,t.ANT_EQUIPMODULE DEVICE_MODEL,FEEDER_TYPE FEEDER_MODEL, COVERTYPE COVERAGE_AREA , null ANTENNA_TYPE_ENUM_ID , CELL_FRES WORKING_FREQUENCY_BAND , TXFEEDER_LENGTH FEEDER_LENGTH , POWER  TRANSMITTING_POWER ,t.ANT_POLARIZE  POLARIZATION_MODE_ENUM_ID ,ant.ANT_VENDOR ANTENNA_MANUFACTURER_ID , t.ACCESS_NET_TIME  PRESENCE_DATE  from NE_CELL_G   t , "
			+ " NE_CELL_ANT ant where t.ne_sys_id=ant.related_cell ";

	private SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-DD hh:mm:ss");

}
