DROP TABLE IF EXISTS  T_SFWNOS_RM_CELL;
CREATE 
	TABLE T_SFWNOS_RM_CELL
 (
	PRI_KEY	VARCHAR(60)	NOT NULL	comment'记录唯一关键字',
	CELL_ID	VARCHAR(100)	NOT NULL	comment'小区标识',
	CARRIER_FREQ_QUANTITY	DECIMAL	comment'载频数量',
	ALIAS	VARCHAR(100)	comment'小区别名',
	LOCATION_AREA_CODE	VARCHAR(100)	NOT NULL	comment'位置区码LAC',
	CELL_CI	VARCHAR(100)	NOT NULL	comment'小区CI',
	DELTA_TYPE	VARCHAR (1)	comment'操作类型',
	OPER_TIME	DATETIME	NOT NULL	comment'操作时间',
	PROVINCE_ID	VARCHAR(100)	NOT NULL	comment'省分ID',
	INSERT_DATA_TIME	DATETIME	NOT NULL	comment'插入时间（ESB使用）',
	RESERVED_1	VARCHAR(240)	comment'预留字段1',
	RESERVED_2	VARCHAR(240)	comment'预留字段2',
	RESERVED_3	VARCHAR(240)	comment'预留字段3',
	RESERVED_4	VARCHAR(240)	comment'预留字段4',
	RESERVED_5	VARCHAR(240)	comment'预留字段5',
	RESERVED_6	VARCHAR(240)	comment'预留字段6',
	RESERVED_7	VARCHAR(240)	comment'预留字段7',
	RESERVED_8	VARCHAR(240)	comment'预留字段8',
	RESERVED_9	VARCHAR(240)	comment'预留字段9',
	RESERVED_10	VARCHAR(240)	comment'预留字段10',
	PRIMARY KEY USING BTREE (PRI_KEY)
)
ENGINE= InnoDB DEFAULT CHARSET= utf8
