package com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv;

import javax.xml.ws.Endpoint;

import com.unicom.ucloud.service.ServiceMgr;

/**
 * This class was generated by Apache CXF 2.2.7 Tue Feb 26 20:20:30 CST 2013 Generated source version: 2.2.7
 */

public class ESBSFWNOSSFWNOSInquiryResInfoSrv_ESBSFWNOSSFWNOSInquiryResInfoSrvPort_Server {

	public ESBSFWNOSSFWNOSInquiryResInfoSrv_ESBSFWNOSSFWNOSInquiryResInfoSrvPort_Server() throws Exception {
		System.out.println("Starting Server");
		Object implementor = new ESBSFWNOSSFWNOSInquiryResInfoSrvImpl();
		ServiceMgr smgr = ServiceMgr.getInstance();
		String addressTmp = smgr.getWebserviceUrl("ESB_SFWNOS_SFWNOS_90001");
		// String address =
		// "http://localhost:8000/nbi/services/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv";

		String address = new String(addressTmp);
		address = address.replace("?wsdl", "").replace("?WSDL", "");

		Endpoint.publish(address, implementor);
	}

	public static void main(String args[]) throws Exception {
		try {
			new ESBSFWNOSSFWNOSInquiryResInfoSrv_ESBSFWNOSSFWNOSInquiryResInfoSrvPort_Server();
			System.out.println("Server ready...");

			// Thread.sleep(50 * 60 * 1000);
			System.out.println("Server exiting");
			// System.exit(0);
		} catch (Exception e) {
			System.out.println("service error . " + e);
		}
	}
}
