package com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7 Tue Feb 26 20:20:30 CST 2013 Generated source version: 2.2.7
 */

@WebService(targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv", name = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE, style = SOAPBinding.Style.DOCUMENT)
public interface ESBSFWNOSSFWNOSInquiryResInfoSrv {

	@WebResult(name = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrvResponse", targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv", partName = "payload")
	@WebMethod(action = "process")
	public ESBSFWNOSSFWNOSInquiryResInfoSrvResponse process(
			@WebParam(partName = "payload", name = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrvRequest", targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv") ESBSFWNOSSFWNOSInquiryResInfoSrvRequest payload);
}
