/*
 * 
 */

package com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.unicom.ucloud.service.ServiceMgr;

/**
 * This class was generated by Apache CXF 2.2.7 Tue Feb 26 20:20:30 CST 2013 Generated source version: 2.2.7
 */

@WebServiceClient(name = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrv",
// wsdlLocation =
// "http://localhost:8080/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv.WSDL",
targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv")
public class ESBSFWNOSSFWNOSInquiryResInfoSrv_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv",
			"ESB_SFWNOS_SFWNOS_InquiryResInfoSrv");

	public final static QName ESBSFWNOSSFWNOSInquiryResInfoSrvPort = new QName("http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv",
			"ESB_SFWNOS_SFWNOS_InquiryResInfoSrvPort");
	static {
		URL url = null;
		try {
			ServiceMgr smgr = ServiceMgr.getInstance();
			String address = smgr.getWebserviceUrl("ESB_SFWNOS_SFWNOS_90001");
			url = new URL(address);
			// url = new
			// URL("http://localhost:8000/nbi/services/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv?wsdl");
		} catch (MalformedURLException e) {
			System.err
					.println("Can not initialize the default wsdl from file:/G:/code/workSpaceEclipse/workSpaceEclipse/nbi_1_ucloub/Web/WEB-INF/META-INF/esb_sfwnos_sfwnos_90001/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv.WSDL");
			// e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		WSDL_LOCATION = url;
	}

	public ESBSFWNOSSFWNOSInquiryResInfoSrv_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ESBSFWNOSSFWNOSInquiryResInfoSrv_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ESBSFWNOSSFWNOSInquiryResInfoSrv_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * @return returns ESBSFWNOSSFWNOSInquiryResInfoSrv
	 */
	@WebEndpoint(name = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrvPort")
	public ESBSFWNOSSFWNOSInquiryResInfoSrv getESBSFWNOSSFWNOSInquiryResInfoSrvPort() {
		return super.getPort(ESBSFWNOSSFWNOSInquiryResInfoSrvPort, ESBSFWNOSSFWNOSInquiryResInfoSrv.class);
	}

	/**
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code>
	 *            parameter will have their default values.
	 * @return returns ESBSFWNOSSFWNOSInquiryResInfoSrv
	 */
	@WebEndpoint(name = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrvPort")
	public ESBSFWNOSSFWNOSInquiryResInfoSrv getESBSFWNOSSFWNOSInquiryResInfoSrvPort(WebServiceFeature... features) {
		return super.getPort(ESBSFWNOSSFWNOSInquiryResInfoSrvPort, ESBSFWNOSSFWNOSInquiryResInfoSrv.class, features);
	}

}
