/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv;

import java.math.BigDecimal;

import javax.xml.ws.Endpoint;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.unicom.ucloud.service.changnotice.ESBSFWNOSSFWNOSInquiryResInfoSrvImplBusiness;

/**
 * This class was generated by Apache CXF 2.2.7 Tue Feb 26 20:20:30 CST 2013 Generated source version: 2.2.7
 */

@javax.jws.WebService(serviceName = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrv", portName = "ESB_SFWNOS_SFWNOS_InquiryResInfoSrvPort", targetNamespace = "http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv",
// wsdlLocation
// ="http://localhost:8080/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv.WSDL",
endpointInterface = "com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv.ESBSFWNOSSFWNOSInquiryResInfoSrv")
public class ESBSFWNOSSFWNOSInquiryResInfoSrvImpl implements ESBSFWNOSSFWNOSInquiryResInfoSrv {

	private static final Logger LOG = LoggerFactory.getLogger(ESBSFWNOSSFWNOSInquiryResInfoSrvImpl.class);

	private final BigDecimal pageCount = new BigDecimal(1000);

	private BigDecimal currPage = new BigDecimal(1);

	private BigDecimal total_record = new BigDecimal(0);

	private BigDecimal totalPage = new BigDecimal(0);

	/*
	 * (non-Javadoc)
	 * 
	 * @seecom.unicom.ucloud.esbsfwnossfwnosinquiryresinfosrv. ESBSFWNOSSFWNOSInquiryResInfoSrv
	 * #process(com.unicom.ucloud.esbsfwnossfwnosinquiryresinfosrv .ESBSFWNOSSFWNOSInquiryResInfoSrvRequest payload )*
	 */
	public com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv.ESBSFWNOSSFWNOSInquiryResInfoSrvResponse process(
			ESBSFWNOSSFWNOSInquiryResInfoSrvRequest payload) {
		LOG.info("Executing operation process");
		System.out.println(payload);
		ESBSFWNOSSFWNOSInquiryResInfoSrvImplBusiness business = new ESBSFWNOSSFWNOSInquiryResInfoSrvImplBusiness();
		ESBSFWNOSSFWNOSInquiryResInfoSrvResponse response = null;
		try {
			response = business.process(payload);
		} catch (Exception ex) {
			LOG.error("esb_sfwnos_sfwnos_inquiryresinfosrv 出现异常，原因: ", ex);
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}

		return response;

	}

	public static void main(String[] args) {
		ESBSFWNOSSFWNOSInquiryResInfoSrvImpl impl = new ESBSFWNOSSFWNOSInquiryResInfoSrvImpl();
		String address = "http://localhost:9000/ESBSFWNOSSFWNOSInquiryResInfoSrvImpl";
		Endpoint.publish(address, impl);

		try {
			Thread.sleep(1000 * 60 * 20);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.exit(0);
		System.out.println("Server exit ");
	}
}