package com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;

import javax.xml.namespace.QName;

import com.unicom.ucloud.util.CalendarConverUtil;

/**
 * This class was generated by Apache CXF 2.2.7 Tue Feb 26 20:20:30 CST 2013 Generated source version: 2.2.7
 */

public final class ESBSFWNOSSFWNOSInquiryResInfoSrv_ESBSFWNOSSFWNOSInquiryResInfoSrvPort_Client {

	private static final QName SERVICE_NAME = new QName("http://ucloud.unicom.com/ESB_SFWNOS_SFWNOS_InquiryResInfoSrv",
			"ESB_SFWNOS_SFWNOS_InquiryResInfoSrv");

	private ESBSFWNOSSFWNOSInquiryResInfoSrv_ESBSFWNOSSFWNOSInquiryResInfoSrvPort_Client() {
	}

	public static void main(String args[]) throws Exception {
		URL wsdlURL = ESBSFWNOSSFWNOSInquiryResInfoSrv_Service.WSDL_LOCATION;
		if (args.length > 0) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ESBSFWNOSSFWNOSInquiryResInfoSrv_Service ss = new ESBSFWNOSSFWNOSInquiryResInfoSrv_Service(wsdlURL, SERVICE_NAME);
		ESBSFWNOSSFWNOSInquiryResInfoSrv port = ss.getESBSFWNOSSFWNOSInquiryResInfoSrvPort();

		{
			System.out.println("Invoking process...");
			com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv.ESBSFWNOSSFWNOSInquiryResInfoSrvRequest request = new ESBSFWNOSSFWNOSInquiryResInfoSrvRequest();

			// SOURCE_APP_ID
			// SOURCE_APP_NAME
			// SOURCE_MOD_ID
			// SOURCE_MOD_NAME
			// TARGET_MOD_ID
			// TARGET_MOD_NAME
			// TOKEN
			// USERID
			// USERNAME
			// SUBMITDATE
			// PAGE_SIZE
			// CURRENT_PAGE
			// TOTAL_RECORD
			// PROVINCE_CODE
			// ENVIRONMENT_NAME

			MsgHeader header = null;
			header = new MsgHeader();
			/**
			 * <pre>	</pre>
			 */
			header.setPAGESIZE(new BigDecimal(1));
			header.setSOURCEAPPID("10");
			header.setSOURCEAPPNAME("11");
			header.setSOURCEMODID("12");
			header.setSOURCEMODNAME("13");
			header.setTARGETMODID("SFWNOS_RM_CELL_REL");
			header.setTARGETMODNAME("SFWNOS_RM_CELL_REL");
			header.setTOKEN("16");
			header.setUSERID(new BigDecimal(1));
			header.setUSERNAME("18");
			header.setSUBMITDATE(CalendarConverUtil.convertToXMLGregorianCalendar(new Date()));
			header.setPAGESIZE(new BigDecimal(500));
			header.setCURRENTPAGE(new BigDecimal(5));
			header.setTOTALRECORD(null);// new BigDecimal(107)
			header.setPROVINCECODE("19");
			header.setENVIRONMENTNAME("20");

			request.setMsgHeader(header);
			request.setEntityName("SFWNOS_RM_ANTENNA_SYSTEM");

			OutputFieldCollection output = new OutputFieldCollection();
			OutputFieldItem item = new OutputFieldItem();
			// item.setOutputFieldName("DEVICE_MODEL");
			item.setOutputFieldName("PHYSICAL_DEVICE_ID");
			output.getOutputFieldItem().add(item);

			QueryConditionCollection query = new QueryConditionCollection();
			QueryConditionItem item2 = new QueryConditionItem();
			// item2.setQueryFieldName("ANTENNA_HEIGHT");
			item2.setQueryFieldName("PHYSICAL_DEVICE_ID");
			item2.setOperation(" <> ");
			item2.setQueryConditionVLAUE("0080307680007030");
			query.getQueryConditionItem().add(item2);
			SortFieldCollection sort = new SortFieldCollection();
			SortFieldItem sItem = new SortFieldItem();
			// sItem.setSortFieldName("PHYSICAL_DEVICE_ID");
			sItem.setSortFieldName("PHYSICAL_DEVICE_ID");
			sItem.setSortMod("ASC");
			sort.getSortFieldItem().add(sItem);

			request.setOutputFieldCollection(output);
			request.setQueryConditionCollection(query);
			request.setSortFieldCollection(sort);

			com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv.ESBSFWNOSSFWNOSInquiryResInfoSrvResponse _process__return = port.process(request);
			System.out.println("process.result=" + _process__return.getSERVICEFLAG().toString());

			System.out.println("dddd");

		}

		System.exit(0);
	}

}
