/*
 * 
 */

package com.unicom.ucloud.esb_rm_m22_inquiryresinfosrv;

import javax.xml.ws.Endpoint;
import javax.xml.ws.WebServiceClient;

import com.unicom.ucloud.esb_sfwnos_sfwnos_inquiryresinfosrv.ESBSFWNOSSFWNOSInquiryResInfoSrvImpl;
import com.unicom.ucloud.service.ServiceMgr;

/**
 * This class was generated by Apache CXF 2.2.7 Mon Apr 08 14:28:02 CST 2013 Generated source version: 2.2.7
 */

@WebServiceClient(name = "ESB_RM_M22_InquiryResInfoSrv",
// wsdlLocation =
// "file:/G:/code/workSpaceEclipse/workSpaceEclipse/nbi_1_ucloub/Web/WEB-INF/META-INF/esb_rm_m22_inquiryresinfosrv/ESB_RM_M22_InquiryResInfoSrv.WSDL",
targetNamespace = "http://ucloud.unicom.com/ESB_RM_M22_InquiryResInfoSrv")
public class ESBRMM22InquiryResInfoSrv_Service_Service {

	public ESBRMM22InquiryResInfoSrv_Service_Service() throws Exception {
		System.out.println("Starting Server");
		/*
		 * Object implementor = new ESBRMM22InquiryResInfoSrvImpl(); ServiceMgr smgr=ServiceMgr.getInstance(); String
		 * addressTmp=smgr.getWebserviceUrl("ESB_RM_M22_90001"); String address = new String(addressTmp); address = address.replace("?wsdl",
		 * "").replace("?WSDL", ""); // String address = "http://localhost:8000/nbi/services/ESB_SFWNOS_SFWNOS_ImportResChangeNoticeInfoSrv" ;
		 * Endpoint.publish(address, implementor);
		 */
	}

	public static void main(String args[]) throws Exception {
		/*
		 * try{ new ESBSFTNMSSFTNMSImportResChangeNoticeInfoSrv_ESBSFTNMSSFTNMSImportResChangeNoticeInfoSrvPort_Server ();
		 * System.out.println("Server ready..."); //Thread.sleep(5 * 60 * 1000); System.out.println("Server exiting"); //System.exit(0); } catch
		 * (Exception e) { System.out.println("Server exiting"); }
		 */
	}
}
